### ISSUE TITLE
Server side code fails with window undefined

### ISSUE THREAD

**Issue by uhef** [formio/react-formio#104]
When running form.io the server side fails with following:

```
/home/tuomjarv/workspace/emedi/kusote/node_modules/formiojs/build/formio.pdf.js:182
window.addEventListener('message', function (event) {
^

ReferenceError: window is not defined
    at Object.<anonymous> (.../node_modules/formiojs/build/formio.pdf.js:182:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (.../node_modules/formiojs/build/formio.full.js:11:16)
    at Module._compile (module.js:570:32)
```

**Comment by uhef** [comment]
This on `react-formio@2.0.0`

**Comment by eruby94** [comment]
This means the component is tightly coupled to the DOM, and doesn't have its own checking for SSR usage. You may need to wrap it in a higher order component like NoSSR (https://github.com/kadirahq/react-no-ssr), or you could fork the code and modify it to only add the listener when the component is rendered in the browser.

**Comment by randallknutson** [comment]
We're currently working on a version of formio.js that will have SSR support. The current version does not. See formio.js 4.x branch.
