### ISSUE TITLE
[BUG] not support SSR yet

### ISSUE THREAD

**Issue by kyawkyawsoezhu** [formio/react-formio#253]
I saw some old issue about ssr, say it will be solve in version 4.x.x but i still got this error,

```
document is not defined
ReferenceError: document is not defined
    at Object.<anonymous> (/usr/src/app/node_modules/dragula/dist/dragula.js:869:23)
    at Object.8 (/usr/src/app/node_modules/dragula/dist/dragula.js:895:4)
    at s (/usr/src/app/node_modules/dragula/dist/dragula.js:1:683)
    at /usr/src/app/node_modules/dragula/dist/dragula.js:1:734
    at Object.<anonymous> (/usr/src/app/node_modules/dragula/dist/dragula.js:724:19)
    at Object.6../eventmap (/usr/src/app/node_modules/dragula/dist/dragula.js:824:4)
    at s (/usr/src/app/node_modules/dragula/dist/dragula.js:1:683)
    at /usr/src/app/node_modules/dragula/dist/dragula.js:1:734
    at Object.<anonymous> (/usr/src/app/node_modules/dragula/dist/dragula.js:41:17)
    at Object.2../classes (/usr/src/app/node_modules/dragula/dist/dragula.js:647:4)
    at s (/usr/src/app/node_modules/dragula/dist/dragula.js:1:683)
    at e (/usr/src/app/node_modules/dragula/dist/dragula.js:1:854)
    at /usr/src/app/node_modules/dragula/dist/dragula.js:1:872
    at i (/usr/src/app/node_modules/dragula/dist/dragula.js:1:150)
    at Object.<anonymous> (/usr/src/app/node_modules/dragula/dist/dragula.js:1:385)
    at Module._compile (module.js:652:30)
```

**Comment by aiwebb** [comment]
@kyawkyawsoezhu, we do not currently support server-side rendering in 4.x, though we _are_ taking incremental steps in that direction.

Components can be instantiated and used in read-only mode on the server with [a handful of shims](https://github.com/formio/formio/blob/15fa0241927c3f3ef56cad41f06013767a5eaf91/src/middleware/submissionHandler.js#L260L265), so we're hopeful that SSR is something we'll be able to deliver in a future version.

**Comment by kyawkyawsoezhu** [comment]
@aiwebb thanks for the explanation.

**Comment by vivekvt** [comment]
I got same error , I am using nextjs.
![Screenshot from 2020-09-23 00-49-11](https://user-images.githubusercontent.com/50275510/93927696-ddd4e600-fd36-11ea-980d-28a589335b81.png)
