### ISSUE TITLE
Server side rendering

### ISSUE THREAD

**Issue by krixerx** [formio/react-formio#65]
When trying to import react-formio:
import Formio from 'react-formio';

following error occures:

C:\Users\kala\workspace\react_fullstack\node_modules\formiojs\node_modules\whatwg-fetch\fetch.js:330
})();
  ^
ReferenceError: self is not defined
    at C:\Users\kala\workspace\react_fullstack\node_modules\formiojs\node_modules\whatwg-fetch\fetch.js:4:7
    at Object.<anonymous> (C:\Users\kala\workspace\react_fullstack\node_modules\formiojs\node_modules\whatwg-fetch\fetch.js:330:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\kala\workspace\react_fullstack\node_modules\formiojs\src\formio.js:9:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\kala\workspace\react_fullstack\node_modules\react-formio\lib\Formio.js:4:16)

**Comment by randallknutson** [comment]
This is actually an issue in the whatwg-fetch module being included by the formio.js module. You can see the issue at https://github.com/github/fetch/pull/253.

To fix this we need to update the whatwg-fetch version in formio.js and repackage in react-formio.

**Comment by randallknutson** [comment]
formio/formio.js#26

**Comment by randallknutson** [comment]
This should be fixed now.
